# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title of this petition')),
                ('slug_name', models.SlugField(max_length=200, null=True, unique=True, verbose_name="Petition's slug name")),
                ('text', models.TextField(verbose_name='Text of this petition')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time when this petition was created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The creator of this petition')),
            ],
        ),
    ]
