# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_auto_20170612_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Разное', 'verbose_name_plural': 'Разное'},
        ),
    ]
