# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_auto_20170613_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Дефолт', 'verbose_name_plural': 'Дефолты'},
        ),
    ]
