# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170212_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='countVoice',
        ),
    ]
