# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170609_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countVoice',
            field=models.IntegerField(default=0),
        ),
    ]
