# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Петиция', 'verbose_name_plural': 'Петиции'},
        ),
    ]
