# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170612_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
    ]
