# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
