# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
